# Generated by Django 5.1.2 on 2024-10-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
